### ISSUE TITLE
BitTorrent Trackers

### ISSUE THREAD

**Issue by alamia442** [lzzy12/python-aria-mirror-bot#116]
how to add BitTorrent reTrackers to aria2?

**Comment by AlbionWhite07** [comment]
@alamia442

**Comment by masbodo** [comment]
`--bt-tracker=<URI>[,...]`

Comma separated list of additional BitTorrent tracker's announce URI. These URIs are not affected by --bt-exclude-tracker option because they are added after URIs in --bt-exclude-tracker option are removed.

example : 

`--bt-tracker=udp://tracker.coppersurfer.tk:6969/announce,udp://tracker.opentrackr.org:1337/announce,http://tracker.opentrackr.org:1337/announce,udp://tracker.leechers-paradise.org:6969/announce`
